version: '3'

services:
  web:
    image: 449515185715.dkr.ecr.us-east-2.amazonaws.com/coin-match:latest
    command: bash -c "python coin_match/manage.py makemigrations && python coin_match/manage.py migrate && python coin_match/manage.py runserver 0.0.0.0:8000"
    container_name: src
    volumes:
      - .:/src
    ports:
      - "8000:8000"