# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exchange_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='exchanges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_trades', to='api.Exchange'),
        ),
    ]
