# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180724_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='watchers',
            field=models.ManyToManyField(related_name='crypto_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
