# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180725_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='admin',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='admin',
            new_name='owner',
        ),
    ]
