# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180725_1151'),
        ('api', '0006_auto_20180725_1726'),
    ]

    operations = [
    ]
