# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20180725_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='owner',
        ),
    ]
