# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180725_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
